version: '3'
services:
  nginx:
    image: nginx:alpine
    volumes: 
      - ./:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - '8000:80'
    environment: 
      - NGINX_HOST=${APP_HOST}
    restart: always
    depends_on: 
      - php
    networks: 
      - app-network
  php:
    build: 
      args: 
        user: ${APP_USER}
        uid: ${APP_UID}
      context: ./
      dockerfile: docker/php/Dockerfile
    image: php:7.4-fpm
    container_name: php
    restart: unless-stopped
    volumes: 
      - ./:/var/www/html
    depends_on: 
      - db
    networks: 
      - app-network
  db:
    image: mysql
    restart: always
    ports:
      - '3306:3306'
    command: --default-authentication-plugin=mysql_native_password
    cap_add: [ SYS_NICE ]
    environment: 
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    networks: 
      - app-network
networks: 
  app-network:
    driver: bridge
